### ISSUE TITLE
[Bug]: cant publish assets

### ISSUE THREAD

**Issue by moghwan** [salahhusa9/laravel-updater#34]
### What happened?

running `php artisan vendor:publish --tag="laravel-updater-config"` doesn't publish the assets:
![image](https://github.com/salahhusa9/laravel-updater/assets/2495180/7f0cf2fe-dc0f-48ab-9b4f-16da502dc5c7)

instead, running `php artisan vendor:publish --provider="Salahhusa9\Updater\UpdaterServiceProvider"` did the job:
![image](https://github.com/salahhusa9/laravel-updater/assets/2495180/573db4ae-1bea-46bc-83ea-44e9236c1165)

a fix has been pushed https://github.com/salahhusa9/laravel-updater/pull/33, [the documentation](https://salahhusa9.com/laravel-updater#installing) should be updated too

### How to reproduce the bug

run `php artisan vendor:publish --tag="laravel-updater-config"`

### Package Version

1.0

### PHP Version

8.2.14

### Laravel Version

10.41.0

### Which operating systems does with happen with?

Linux

**Comment by salahhusa9** [comment]
thank you for your contribution, i will remove migration because it unused.

**Comment by salahhusa9** [comment]
fixed: #36
