### ISSUE TITLE
Docs pages not found [Bug]: 

### ISSUE THREAD

**Issue by Taoshan98** [salahhusa9/laravel-updater#35]
### What happened?

In the docs website, page for 'Pipelines' and 'advance use' in after update section respond to 404.

![image](https://github.com/salahhusa9/laravel-updater/assets/15851056/d6d83c77-1852-4902-93ce-6bb4826b3ea1)

### How to reproduce the bug

Go to update section and click the links

### Package Version

0

### PHP Version

0

### Laravel Version

0

### Which operating systems does with happen with?

Windows

**Comment by salahhusa9** [comment]
can you send me url

**Comment by salahhusa9** [comment]
and where you find this url?
