### ISSUE TITLE
[Bug]: git fetch fails with getaddrinfo() thread failed to start

### ISSUE THREAD

**Issue by itsmenewbie03** [salahhusa9/laravel-updater#48]
### What happened?

I'm trying to use `Updater::update()` however it fails.
![image](https://github.com/salahhusa9/laravel-updater/assets/89230263/45ea4409-1453-434c-875e-cf3e50ff61e1)
However the update works fine if you use the terminal command.
![image](https://github.com/salahhusa9/laravel-updater/assets/89230263/1a2ef8d8-4d03-4db2-9a70-786ed4c49a3d)

### How to reproduce the bug

Use `Updater::update()` on windows.

### Package Version

latest

### PHP Version

8.2.12

### Laravel Version

10

### Which operating systems does with happen with?

Windows

### Notes

The `Update::update()` works fine in my linux machine but it fails on my teammate who uses windows.

**Comment by salahhusa9** [comment]
this problem is from DNS

**Comment by salahhusa9** [comment]
check this https://github.com/desktop/desktop/issues/17755
