### ISSUE TITLE
Publish of config file doesn't work

### ISSUE THREAD

**Issue by VisionovaDev** [salahhusa9/laravel-updater#51]
### What happened?

The documentation says to run 
``` php artisan vendor:publish --tag="laravel-updater-config" ``` 
to publish the config file but it doesn't work.
The error is : 

"No publishable resources for tag [laravel-updater-config]."

### How to reproduce the bug

Install Laravel 11, the package and run the command 
``` php artisan vendor:publish --tag="laravel-updater-config" ``` 

### Package Version

1.2

### PHP Version

8.3.6

### Laravel Version

11

### Which operating systems does with happen with?

Linux

**Comment by salahhusa9** [comment]
Yes there is a mistake, this is correct
`php artisan vendor:publish --tag="updater-config"`

**Comment by salahhusa9** [comment]
[Changed in docs](https://github.com/salahhusa9/laravel-updater/commit/088c42f5c25ce41501c74f877ba851c4b22f063f)
